sudo: false  
language: go  
git:  
    depth: 1  
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.65.2/hugo_0.65.2_Linux-64bit.deb
  - sudo dpkg -i hugo_0.65.2_Linux-64bit.deb
script:  
    ‐ hugo  
deploy:  
    provider: pages  
    skip_cleanup: true  
    github_token: $GITHUB_TOKEN  
    on:  
        branch: master  
    local_dir: public  
    repo: jonyhy96/jonyhy96.github.io  
    target_branch: master  
    email: hy352144278@gmail.com
    name: jonyhy96
